set -g mouse on

prfx="#{?client_prefix,<Prefix active> ,}"
set -g status-left "${prfx}"

set -g pane-border-status top
set -g pane-border-format " [###P #T] ${prfx}"

unbind r
bind-key r source-file ~/.tmux.conf \; display-message "tmux.conf reloaded.."

unbind C-b
set-option -g prefix C-Space

bind S-c command-prompt -p "New session / Change to:" "new-session -A -s '%%'"

bind-key -n C-S-Left swap-window -t -1
bind-key -n C-S-Right swap-window -t +1

bind-key | split-window -h
bind-key - split-window -v

bind -n M-Left  select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up    select-pane -U
bind -n M-Down  select-pane -D

bind -n M-S-Left  resize-pane -L 5
bind -n M-S-Right resize-pane -R 5
bind -n M-S-Up    resize-pane -U 2
bind -n M-S-Down  resize-pane -D 2

bind -n Escape-Left  select-pane -L
bind -n Escape-Right select-pane -R
bind -n Escape-Up    select-pane -U
bind -n Escape-Down  select-pane -D

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @plugin 'dracula/tmux'
set -g @dracula-show-powerline false
set -g @dracula-show-left-icon session
set -g @dracula-show-timezone false
set -g @dracula-military-time true
set -g @dracula-time-format "%Y%m%d %k%M"
set -g @dracula-plugins "cpu-usage ram-usage time"

run '~/.tmux/plugins/tpm/tpm'
