#-------------------------------#
#          NYTTIG INFO          #
#-------------------------------#
#
# C = CTRL
# M = ALT
# S = SHIFT
# prefix = en forhåndsbestemt tastekombinasjon
#
# Tastekombinasjonsmuligheter
# CTRL + SHIFT
# CTRL + ALT
# SHIFT + ALT
# CTRL + SHIFT + ALT
#
# Det er forskjell på "bind" og "bind-key" og "bind -n".
# bind     = brukes til å knytte en tast til en kommando, f.eks. "bind C-a xxxxxx" gjør at tastekombinasjon CTRL + A settes til å gjøre noe.
# bind-key = brukes til å knytte en tast til prefix bindingen, f.eks. "bind-key r xxxx" blir trigget når prefix + r blir trykket.
# bind -n  = brukes til å knytte en tast og samtidig si at du ikke skal bruke prefix
#
# Må finne ut forskjellen på set / set-option
# 
# 
# 
# 
# 

#----------------------------------#
#          GLOBAL CONFIGS          #
#----------------------------------#

# Mouse Mode enabled (select window, pane and resize pane are now possible)
set -g mouse on
